#!/bin/bash
# boot_make_vsh
mkfifo pipe0
mkfifo pipe1
mkfifo pipe2
mkfifo pipe3
mkfifo pipe4
./boot_run_queries 4>pipe2 3<pipe1 &
boot_run_queries_pid=$!
./boot_emit_bash 4>pipe3 3<pipe2 &
boot_emit_bash_pid=$!
./boot_create_rect_facts 4>pipe4 3<pipe0 &
boot_create_rect_facts_pid=$!
./boot_permissions_to_execute  3<pipe3 &
boot_permissions_to_execute_pid=$!
./boot_sort_factbase 4>pipe1 3<pipe4 &
boot_sort_factbase_pid=$!
./boot_drawio_to_factbase 4>pipe0  &
boot_drawio_to_factbase_pid=$!
wait $boot_run_queries_pid
wait $boot_emit_bash_pid
wait $boot_create_rect_facts_pid
wait $boot_permissions_to_execute_pid
wait $boot_sort_factbase_pid
wait $boot_drawio_to_factbase_pid
rm pipe0
rm pipe1
rm pipe2
rm pipe3
rm pipe4
