#!/bin/bash
# bounding_boxes
read baton </dev/fd/3
echo '@@ bounding boxes' 1>&2
cp fb.pl _2.pl
swipl -q -g 'consult(fb).' -g 'consult(boundingBoxes).' -g 'printBB.'  -g 'halt.' | ./augment-fb.bash
echo baton >/dev/fd/4








