#!/bin/bash
# create_rect_facts
read </dev/fd/3
## create rect fact for every vertex that is not an edge/ellipse/text
## sequence.drawio file contains vertexes, and marks all edge and ellipse (and text)
## but does not mark rectangles (the default)
## this pass finds the defaults and creates explicit rect(...) facts
swipl -q \
   -g 'consult(5).' \
   -g 'consult(rects).' \
   -g 'printRects.' \
   -g 'halt.' \
   > 16.pl
echo done >/dev/fd/4








