#!/bin/bash
# d2pl
cdir=`pwd`
pfr $1.drawio drawio.ohm drawio.glue $cdir/support.js \
  | pfr - styleexpander.ohm styleexpander.glue $cdir/support.js \
  | pfr - attributeelider.ohm attributeelider.glue $cdir/support.js \
  | pfr - emitFactbase.ohm emitFactbase.glue $cdir/support.js \
  | sort > /dev/fd/4






