#!/bin/bash
# design_rule_rectangles_must_not_intersect
read baton </dev/fd/3
swipl -q \
   -g 'consult(fb).' \
   -g 'consult(onSameDiagram).' \
   -g 'consult(designRuleRectanglesMustNotIntersect).' \
   -g 'designRuleRectanglesMustNotIntersectOnTheSameDiagram.' \
   -g 'halt.' \
  | ./check-design-rule.bash 
echo baton >/dev/fd/4









