#!/bin/bash
# make_vsh
mkfifo pipe0
mkfifo pipe1
mkfifo pipe2
mkfifo pipe3
mkfifo pipe4
./run queries 4>pipe2 3<pipe1 &
run queries_pid=$!
./emit bash 4>pipe3 3<pipe2 &
emit bash_pid=$!
./create rect facts 4>pipe4 3<pipe0 &
create rect facts_pid=$!
./permissions to execute  3<pipe3 &
permissions to execute_pid=$!
./sort factbase 4>pipe1 3<pipe4 &
sort factbase_pid=$!
./drawio to factbase 4>pipe0  &
drawio to factbase_pid=$!
wait $run queries_pid
wait $emit bash_pid
wait $create rect facts_pid
wait $permissions to execute_pid
wait $sort factbase_pid
wait $drawio to factbase_pid
rm pipe0
rm pipe1
rm pipe2
rm pipe3
rm pipe4
