#!/bin/bash
# port_directions
read baton </dev/fd/3
swipl -q \
   -g 'consult(fb).' \
   -g 'consult(onSameDiagram).' \
   -g 'consult(portdirection).' \
   -g 'printAllDirections.' \
   -g 'halt.' \
  | ./augment-fb.bash 
echo baton >/dev/fd/4









