#!/bin/bash
# port_contains
read baton </dev/fd/3
echo '@@ port contains' 1>&2
cp fb.pl _8.pl
swipl -q -g 'consult(fb).' -g 'consult(onSameDiagram).' -g 'consult(containsport).' -g 'printAllPortContains.' -g 'halt.' | ./augment-fb.bash 
echo baton >/dev/fd/4










