#!/bin/bash
# port_contains
read baton </dev/fd/3
swipl -q \
  -g 'consult(fb).' \
  -g 'consult(onSameDiagram).' \
  -g 'consult(containsport).' \
  -g 'printAllPortContains.' \
  -g 'halt.' \
  | ./augment-fb.bash 
echo baton >/dev/fd/4









