#!/bin/bash
# sync_code
read baton </dev/fd/3
swipl -q \
   -g 'consult(fb).' \
   -g 'consult(onSameDiagram).' \
   -g 'consult(component).' \
   -g 'consult(code).' \
   -g 'printCode.' \
   -g 'halt.' \
  | ./augment-fb.bash 
echo baton >/dev/fd/4









