#!/bin/bash
# transpile_drawio_to_swipl
pipe0=pipe${RANDOM}
mkfifo $pipe0
pipe1=pipe${RANDOM}
mkfifo $pipe1
pipe2=pipe${RANDOM}
mkfifo $pipe2
pipe3=pipe${RANDOM}
mkfifo $pipe3
pipe4=pipe${RANDOM}
mkfifo $pipe4
pipe5=pipe${RANDOM}
mkfifo $pipe5
./d2pl  $1   4>$pipe4 &
d2pl_pid=$!
./create_rect_facts   3<$pipe4 4>$pipe5 &
create_rect_facts_pid=$!
./make_fb   3<$pipe5 4>$pipe0 &
make_fb_pid=$!
./bounding_boxes   3<$pipe0 4>$pipe3 &
bounding_boxes_pid=$!
./all_contains_1   3<$pipe2 4>$pipe1 &
all_contains_1_pid=$!
./make_fb_containing_bounding_boxes   3<$pipe3 4>$pipe2 &
make_fb_containing_bounding_boxes_pid=$!
./fini   3<$pipe1  &
fini_pid=$!
wait $d2pl_pid
wait $create_rect_facts_pid
wait $make_fb_pid
wait $bounding_boxes_pid
wait $all_contains_1_pid
wait $make_fb_containing_bounding_boxes_pid
wait $fini_pid
rm $pipe0
rm $pipe1
rm $pipe2
rm $pipe3
rm $pipe4
rm $pipe5





